services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - stack.env
    restart: always
    container_name: HayaseDB-bot
    pull_policy: build
    volumes:
      - ./src:/app/src

  mongo:
    image: mongo:latest
    container_name: HayaseDB-bot-db
    restart: always
    env_file:
      - stack.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    attach: false

volumes:
  mongo-data: