services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    restart: always
    container_name: HayaseDB-bot
    pull_policy: build
    volumes:
      - ./src:/app/src

  mongo:
    image: mongo:latest
    container_name: HayaseDB-bot-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    attach: false

volumes:
  mongo-data: