
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - stack.env
    restart: always
    container_name: HayaseDB-bot
    pull_policy: build

  mongo:
    image: mongo:latest
    container_name: HayaseDB-bot-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - stack.env
    attach: false

volumes:
  mongo-data:


